### PR TITLE
Add cfLocal.

### PR DESCRIPTION
**Pull request by smillst**

### CODE REVIEW

**Comment by mernst** [comment]
@smillst Is this needed in every plume-lib project?  I assume so.

**Comment by mernst** [comment]
Also, is this fixing the build failure in https://github.com/typetools/checker-framework/pull/2846?
(Why is that failure a NullPointerException?  What has to be done to make that NullPointerException an easier-to-understand error?)

**Comment by smillst** [comment]
`cfLocal` is needed in every plume-lib project.  I added it to every project, but I think that was before this project existed.

**Comment by smillst** [comment]
The NPE is in the build.gradle because it is asking for tools.jar that doesn't exist in JDK 11.  I can fix that, but this project won't build with both JDK 8 and JDK 11 because it uses com.sun.tools.doclets.standard.Standard which has moved in JDK 11.  We will need to skip this project in when testing with JDK 11.

**Comment by mernst** [comment]
I am in the middle of rewriting plume-lib projects to use JDK 11 classes.  That won't be complete this week, unfortunately -- it's a bigger task than I had hoped.

**Comment by smillst** [comment]
I made the Checker Framework test skip require-javadoc if testing with JDK 11: https://github.com/typetools/checker-framework/pull/2836

And finally the plume-lib jdk11 tests pass on that branch!

**Comment by mernst** [comment]
Closed by separate refactoring to make plume-lib's build.gradle files consistent with one another.

**Pull request closed without merging**
